Fixed NullReferenceException: Ridigbody2D ridigbody was null in Update(); Problem: Typo in Method Start(): void start() --> void Start()
NullReferenceException: Object reference not set to an instance of an object
TapController.Update () (at Assets/My Game/Scripts/TapController.cs:31)